class Solution:
    def findTheDifference(self, s: str, t: str) -> str:
        """
        Finds the character that was added to t when it was generated by shuffling s and adding one more letter at a random position.

        Args:
            s: A string.
            t: A string.

        Returns:
            The character that was added to t.
        """
        count = Counter(s)

        for i, c in enumerate(t):
            count[c] -= 1
            if count[c] == -1:
                return c

## 389. Find the Difference
